name: Build & Push FE Docker Image

# fe-build-push.yml
on:
  push:
    branches: [ "main" ]
    paths:
      - "static/**"
      - "templates/**"
      - "Dockerfile" 
      - ".github/workflows/fe-build-push.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build FE Docker image
        run: |
          docker build -t alyanmo/devops-fe:latest .

      - name: Push FE Docker image
        run: |
          docker push alyanmo/devops-fe:latest