name: Build & Push FE Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - "static/**"
      - "index.html"
      - "app.js"
      - "styles.css"
      - "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build FE Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-todo-frontend:latest .

      - name: Push FE Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-todo-frontend:latest